name: Scan Scheduler

on:
  # schedule:
  #   - cron: '0 14 * * 6'  # 9 AM EST
  workflow_dispatch:

jobs:
  scan-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Scheduler Script
        env:
          GITHUB_TOKEN: ${{ secrets.SCHEDULER_TOKEN }}  # Use your PAT here
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: python scheduler.py

      - name: Commit Updated Scan Results
        if: success()
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git pull
          git add scan_results.json
          git commit -m "Update scan results [skip ci]" || echo "No changes"
          git push
